### PR TITLE
[FIX] resurrected python2.6 support

### PR DESCRIPTION
**Pull request by weese**
Hi,

although it is stated on the website. PyHDB doesn't work with Python 2.6 due to some dependencies on features introduced in 2.7. I replaced by 2.6 features and now it works for me.

Cheers,
David

### CODE REVIEW

**Comment by TwoLaid** [comment]
nice job! I hope this gets merged soon and then someone could even update the pip package :)

**Comment by ralhei** [comment]
Thanks for the patch - looks fine to me. I would vote for applying the pull request.

**Comment by weese** [comment]
Hi,

it there anything that should be done before this PR can be merged? Otherwise, I would also vote for the merge ;-)

Cheers,
Dave

**Comment by jarus** [comment]
Did someone tests with other Python versions like 2.7/3.3/3.4?

**Comment by jarus** [comment]
But first of all, thank you for your contribution.

**Comment by jarus** [comment]
I tested your changes and sadly found some problems with the LOB support.

@ralhei You are the LOB expert. Could you please take a look?

**Comment by ralhei** [comment]
@jarus: Can you give me a hint what kind of problem you have? I need to know what you have tried to do ...

**Comment by weese** [comment]
Hmm, the only changes I did was to replace constants from package io by constants from os with the same values and to use slightly longer syntax to remove "hana_" prefixes from command line arguments. I am surprised that this might have side-effects on LOB.

**Comment by weese** [comment]
I just merged master into my PR and fixed an issue with python 3.x, i.e. replaced iteritems() by items().

**Comment by weese** [comment]
And I just verified manually, that the change in ```pyhdb/__init__.py``` works for python-2.6 as well as for python-3.4.

**Comment by jarus** [comment]
The main problem of supporting python 2.6 is the missing unicode support of `io.StringIO`. We can think about to support Python 2.6 again but without NCLOB support.

**Comment by jarus** [comment]
As Python 2.6 is now at its end of live. Let's close this pull request.

**Pull request closed without merging**
