### PR TITLE
Allow encrypted connections

### PR DESCRIPTION
**Pull request by rlindner81**
This is _required_ for working with SAP CF "HANA as a service"
https://jam4.sapjam.com/groups/uc0iP4nx2f9Gm9VsksODsy

I also increased the maximal message size since we found this to be too low in some cases.

See https://github.com/SAP/PyHDB/issues/107

### CODE REVIEW

**Comment by angelcaido19** [comment]
@ralhei @jarus Guys, do you have an idea if this PR is going to be merge soon?

**Comment by cdeil** [comment]
I also need this. I fetched this branch via
```
pip install git+https://github.com/rlindner81/PyHDB.git@fb_ssl_connection
```
and tried a `pyhdb.connect` with `encrypt=True`.
It results in this error:
```
$ python analyse/hackdays.py 
Traceback (most recent call last):
  File "analyse/hackdays.py", line 46, in <module>
    read_table_pyhdb()
  File "analyse/hackdays.py", line 33, in read_table_pyhdb
    encrypt=True,
  File "/Users/deil/software/anaconda3/envs/hackdays/lib/python3.7/site-packages/pyhdb/__init__.py", line 30, in connect
    conn.connect()
  File "/Users/deil/software/anaconda3/envs/hackdays/lib/python3.7/site-packages/pyhdb/connection.py", line 155, in connect
    self._open_socket_and_init_protocol()
  File "/Users/deil/software/anaconda3/envs/hackdays/lib/python3.7/site-packages/pyhdb/connection.py", line 84, in _open_socket_and_init_protocol
    self._socket = context.wrap_socket(self._socket, server_hostname=self.host)
  File "/Users/deil/software/anaconda3/envs/hackdays/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Users/deil/software/anaconda3/envs/hackdays/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Users/deil/software/anaconda3/envs/hackdays/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)
```
Is there a fix for this certificate issue?

**Comment by rlindner81** [comment]
@cdeil Use `encrypt_verify=False` on the .connect() call to disable certificate verification.

**Comment by cdeil** [comment]
@rlindner81 - Thank you!

Indeed, the `encrypt=True, encrypt_verify=False` options did the trick:
```
    connection = pyhdb.connect(
        host="...",
        port=...,
        user="...",
        password="...",
        encrypt=True,
        encrypt_verify=False,
    )
```

@jarus - Can you have a look / merge this in soon?

**Comment by clivant** [comment]
Hi all, this seems like the solution to connect to Hana service on Cloud Foundry. Can this be introduced in a new release for this project?

**Comment by caikn** [comment]
It works for me also. please include it in the new release.

**Comment by cdeil** [comment]
Is `PyHDB` alive or dead? (no update for the past year)

It's important for data scientists to connect to HANA from Python for some tasks.

@SAP - Please merge this PR!

**Comment by rlindner81** [comment]
@cdeil I think PyHDB should stop. AFAIK the official Hana drivers for python can now be installed through pip and those should be used instead.

**Comment by cdeil** [comment]
@rlindner81 - Ah, OK.

It would be very useful if this is clarified in the README.
(and maybe close open PRs and issues so that people interested get a notification).

**Comment by rlindner81** [comment]
Agreed, @jarus should do some cleanup.

Anyway if anyone finds their way here. This is the way forward:
https://blogs.sap.com/2019/06/25/sap-hana-official-python-driver-is-on-pypi/

I will close this PR as irrelevant.

**Comment by cdeil** [comment]
@rlindner81 @jarus - Could you please do a quick README update here pointing people to the right repo?

Looking at https://github.com/SAP/PyHDB it still seems that this is the package to use to connect to HANA from Python.

**Pull request closed without merging**
